#!/usr/bin/env sh

cask electric-sheep

# Set as screensaver if it isn't already
if dot::installing && \
   !(defaults -currentHost read com.apple.screensaver \
     | grep "Electric Sheep" >/dev/null 2>&1)
then
  defaults -currentHost write com.apple.screensaver moduleDict -dict \
    moduleName "Electric Sheep" \
    path "/Library/Screen Savers/Electric Sheep.saver"
fi
