#!/usr/bin/env sh

if [ "$DOT_SHELL" = zsh ]; then
  dot::repo "git://github.com/zsh-users/zsh-completions.git"
  dot::repo "git://github.com/zsh-users/zsh-syntax-highlighting.git" "$DOT_PLUGIN_DIR/zsh-syntax-highlighting" "3dc57419"
  dot::repo "git://github.com/zsh-users/zsh-history-substring-search.git"
fi
